tasks:
  - init: |
      rustup target add wasm32-unknown-unknown
      npm install -g near-cli
      cd frontend
      npm install
  - command: |
      cd frontend
      npm run dev -- -H 0.0.0.0 -p 3000
